version: "3.9"

services:
  redis:
    image: redis:7.4-alpine
    container_name: rrfusion-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - rrfusion-net
    volumes:
      - redis-data:/data

  # --- To be added later by Codex/devs ---
  db-stub:
    build: ../apps/db_stub
    container_name: rrfusion-db-stub
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - rrfusion-net

  # mcp host is now launched via `uv run fastmcp run --transport http src/rrfusion/mcp/host.py`
  # once the DB stub + Redis are healthy. Add a dedicated service here if you
  # later decide to containerize the FastMCP process again.

networks:
  rrfusion-net:
    driver: bridge

volumes:
  redis-data:
    driver: local
