version: "3.9"

services:
  redis:
    image: redis:7.4-alpine
    container_name: rrfusion-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - rrfusion-net
    volumes:
      - redis-data:/data

  db-stub:
    build:
      context: ..
      dockerfile: apps/db_stub/Dockerfile
    container_name: rrfusion-db-stub
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python -c \"import urllib.request; urllib.request.urlopen('http://127.0.0.1:8080/healthz')\"",
        ]
      interval: 10s
      timeout: 5s
      retries: 12
    networks:
      - rrfusion-net

  mcp:
    build:
      context: ..
      dockerfile: apps/mcp-host/Dockerfile
    container_name: rrfusion-mcp
    env_file: .env
    command:
      [
        "fastmcp",
        "run",
        "--transport",
        "http",
        "src/rrfusion/mcp/host.py",
        "--",
        "--host",
        "0.0.0.0",
        "--port",
        "3000",
      ]
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
      db-stub:
        condition: service_healthy
    networks:
      - rrfusion-net

  tests:
    build:
      context: ..
      dockerfile: apps/mcp-host/Dockerfile
    container_name: rrfusion-tests
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
      db-stub:
        condition: service_healthy
    networks:
      - rrfusion-net
    profiles: ["tests"]

networks:
  rrfusion-net:
    driver: bridge

volumes:
  redis-data:
    driver: local
